controller:
  # Service info:
  # https://github.com/helm/charts/tree/master/stable/nginx-ingress#additional-internal-load-balancer
  service:
    external:
      enabled: true
    internal:
      enabled: false
      annotations:
        # Create internal LB. More informations: https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing
        # For GKE versions 1.17 and later
        networking.gke.io/load-balancer-type: "Internal"
        # For earlier versions
        # cloud.google.com/load-balancer-type: "Internal"

        # Any other annotation can be declared here.