
resource "google_compute_global_address" "gitlab" {
  project       = var.project_id
  name          = "${var.environment}-db-ip"
  purpose       = "VPC_PEERING"
  address_type  = "INTERNAL"
  network       = var.network.id
  prefix_length = 16
}

resource "google_service_networking_connection" "private_vpc_connection" {
  network                 = var.network.id
  service                 = "servicenetworking.googleapis.com"
  reserved_peering_ranges = [google_compute_global_address.gitlab.name]
}

resource "random_string" "autogenerated_gitlab_db_name" {
  length  = 5
  number  = false
  upper   = false
  special = false
}

resource "google_sql_database_instance" "gitlab" {
  name             = "${var.environment}-db-${random_string.autogenerated_gitlab_db_name.result}"
  project          = var.project_id
  region           = var.region
  database_version = "POSTGRES_14"

  settings {
    tier            = var.tier
    disk_autoresize = true

    ip_configuration {
      ipv4_enabled    = "false"
      private_network = var.network.id
    }

    database_flags {
      name  = "max_connections"
      value = "200"
    }

    database_flags {
      name  = "shared_buffers"
      value = "13107"
    }
  }
  depends_on = [google_service_networking_connection.private_vpc_connection]
  # TEMP TUNNING
  deletion_protection = false
}

# GitLab database
resource "random_string" "autogenerated_gitlab_db_password" {
  length  = 16
  special = false
}

resource "google_sql_user" "gitlab" {
  name     = "gitlab"
  instance = google_sql_database_instance.gitlab.name
  password = random_string.autogenerated_gitlab_db_password.result
}

resource "google_sql_database" "gitlab" {
  name       = "${var.environment}-gitlab-production"
  instance   = google_sql_database_instance.gitlab.name
  depends_on = [google_sql_user.gitlab]
}

# SonarQube database
resource "random_string" "autogenerated_sonarqube_db_password" {
  length  = 16
  special = false
}

resource "google_sql_user" "sonarqube" {
  name     = "sonarqube"
  instance = google_sql_database_instance.gitlab.name
  password = random_string.autogenerated_sonarqube_db_password.result
}

resource "google_sql_database" "sonarqube" {
  name       = "${var.environment}-shared-sonarqube-production"
  instance   = google_sql_database_instance.gitlab.name
  depends_on = [google_sql_user.sonarqube]
}
